### ISSUE TITLE
GA id 更換

### ISSUE THREAD

**Issue by aszx87410** [StarBugsWeekly/recommended_article#1]
Hi, 因為目前你們 GA 的 id 還沒換掉，還是用原本我們 cymetrics tech blog 的，因此我們 GA 會混到一些這邊的流量：https://github.com/StarBugsWeekly/recommended_article/blob/main/_data/metadata.json#L7

再麻煩找時間更新一下，感謝！

**Comment by LarryLuTW** [comment]
謝謝你的回報～我剛剛改好了，不好意思
